### ISSUE TITLE
Problems reproducing the I2I results in the paper

### ISSUE THREAD

**Issue by woodfrog** [google-research-datasets/Crisscrossed-Captions#1]
Hi,

Thanks for sharing the great dataset! 

I'm trying to implement the evaluation pipeline based on the released annotations, and I'm using the official VSRN (the "VSRN-github" entry in your original paper) to verify the correctness of my implementation. I have successfully reproduced the I2T, T2I, and T2T numbers, but got some problems on I2I.  Using the positive annotations available in "sis_test.csv", the Recalls I got are lower than the ones reported in the paper, so I guess I might miss some details in my current implementation.

There are several questions that I want to confirm:
(1). Do you use the annotations in SITS or STS to augment the positive pairs for I2I? For example, if there are two positive image-text pairs (i1, t1), (i2, t1) in the SITS annotation, will you consider (i1, i2) as a positive I2I pair? Or if (t3, t4) is a positive caption pair in the STS annotation, and they belong to two different MS-COCO images i3 and i4, will you consider (i3, i4) as a positive I2I pair? 
(2). There are 5,000 images in the test set, but some of them do not have any associated positive pairs in the annotation. For these images, do you still include them in the retrieval process? If yes, then how do you evaluate the retrieval results for them?

Thank you and looking forward to your reply!

**Comment by hexiang-hu** [comment]
Same question here.

**Comment by clrrrr** [comment]
Hi, same questions here, have you found the answer?

**Comment by Zarana-Parekh** [comment]
For image-image pairs, the positive pairs should be thresholded at a CxC score of 2.5. For text-text and image-text the threshold is 3.
